version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fantaroom_user
      POSTGRES_PASSWORD: fantaroom_pass
      POSTGRES_DB: fantaroom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
